### ISSUE TITLE
Event Management [Configure a specific retry_ttl fo some queues]

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#130]
Imagine we configure two subscribers on `UserCreated` event:

```yml
events:
  publish_deploy_event: True
  message_broker: rabbitmq
  organization: alice
  service: onboarding
  subscribers:
    UserCreated:
      version: 1
      handlers:
       - petisco.src.modules.mails.application.send_mail_on_user_created.send_mail_on_user_created
       - petisco.src.modules.webhooks.application.send_webhook_on_user_created.send_webhook_on_user_created
```

Now, with default configuration, `retry_ttl` is 5000 ms. We can change it adding following code:

```yml
events:
   retry_ttl: 10000
   ...
```

What happens if we want to `send_mail_on_user_created` handler stays with the same configuration and `send_webhook_on_user_created` has another one. Should we take this into account on next version?

One option:

```yml
events:
  publish_deploy_event: True
  message_broker: rabbitmq
  organization: alice
  service: onboarding
  subscribers:
    UserCreated:
      version: 1
      handlers:
       - petisco.src.modules.mails.application.send_mail_on_user_created.send_mail_on_user_created
       - petisco.src.modules.webhooks.application.send_webhook_on_user_created.send_webhook_on_user_created
specific_queues_config:
   webhooks:
       retry_ttl: 10000
       queues: petisco.service.1.event.user_created.send_webhook_on_user_created

```

**Comment by acostapazo** [comment]
Other option:



One option:

```yml
events:
  publish_deploy_event: True
  message_broker: rabbitmq
  organization: alice
  service: onboarding
  subscribers:
    UserCreated:
      version: 1
      handlers:
       - petisco.src.modules.mails.application.send_mail_on_user_created.send_mail_on_user_created
       - petisco.src.modules.webhooks.application.send_webhook_on_user_created.send_webhook_on_user_created
specific_queues_config:
   webhooks:
       retry_ttl: 10000
       queues_containing: *send_webhook*

```

**Comment by acostapazo** [comment]
```yml
specific_queues_config:
   webhooks:
       when_queue_contain: *send_webhook*
       use:
           retry_ttl: 10000
           main_ttl: 1000
```
