### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#137]
`Petisco` application and persistence management are too coupled, so maybe create an isolated `Persistence`module helps.

As an user, it seems using the module in the following manner, make sense :) 

```python
database = SqliteDatabase("sql.persistence.models.yml") # or database = MySqlDatabase()
persistence = Persitence() 
persistence.add("sql", database)
persistence.create()
persitence.delete()
model = Persitence.get_database("sql").get_model("model") # from yml
```

Where `sql.persistence.models.yml` could be something like:

```yml
 models:
      authentication: onboardingrest.src.modules.kyc.authentication.shared.infrastructure.repositories.database.authentication_model.AuthenticationModel
      media: onboardingrest.src.modules.kyc.media.retrieve.infrastructure.repositories.database.media_model.MediaModel
      client: onboardingrest.src.modules.shared.client.infrastructure.repositories.database.client_model.ClientModel
      client_config: onboardingrest.src.modules.kyc.client_config.infrastructure.repositories.database.client_config_model.ClientConfigModel
      document: onboardingrest.src.modules.shared.user.infrastructure.repositories.database.document_model.DocumentModel
      document_side: onboardingrest.src.modules.shared.user.infrastructure.repositories.database.document_side_model.DocumentSideModel
      face_info: onboardingrest.src.modules.shared.user.infrastructure.repositories.database.face_info_model.FaceInfoModel
      face_profile: onboardingrest.src.modules.shared.user.infrastructure.repositories.database.face_profile_model.FaceProfileModel
      report: onboardingrest.src.modules.kyc.report.retrieve.infrastructure.repositories.database.report_model.ReportModel
      user: onboardingrest.src.modules.shared.user.infrastructure.repositories.database.user_model.UserModel
      certificate: onboardingrest.src.modules.kyc.certificate.shared.infrastructure.repositories.database.certificate_model.CertificateModel
      forensics_analysis: onboardingrest.src.modules.kyc.document.forensics.infrastructure.repositories.database.forensics_analysis_model.ForensicsAnalysisModel
      screening_result: onboardingrest.src.modules.screening.shared.infrastructure.repositories.database.screening_result_model.ScreeningResultModel
```

It would be awesome having a command on petisco to get every model from a directory and update the model.yml

```bash
petisco --create-model-file sql.persistence.models.yml --from-source petisco/
```
