### ISSUE TITLE
Add Subscribers/EventConsumers

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#32]
Declare events subscriber in petisco.yml

```yml
   event_manager:
          provider: myservice.config.event_manager_provider.event_manager_provider
          event_subscriber:
                event_store:
                    handler: myservice.modules.event.store.event_store_handler
                    topics:
                       - topic1
                       - topic2
```
