### ISSUE TITLE
Refactor Event dumping to be json:api compilant

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#35]
```python
    class UserCreated(Event):
        user_id: UserId

        def __init__(self, user_id: UserId):
            self.user_id = user_id
            self.event_version = "1"
            super().__init__()
```

payload = UserCreated(UserId.generate()).to_dict()

```yml
{
"user_id": "userpwlxU3yGsird", 
"event_version": "1", 
"event_id": "968a1", 
"event_name": "user.created", 
"event_occurred_on": "2020-04-27 08:53:37.488377"
}
```

What if we change it to be `{json:api}` compilant. https://jsonapi.org/

In this case:

```yml
{
"data": {
    "id": "968a1",
    "type": "organization.service.1.user.created",
    "ocurred_on": "2020-04-27 08:53:37.488377",
    "attributes": {
      "user_id": "userpwlxU3yGsird"
    }
    "meta": {
         host: "localhost"
     }
}
}
```
