### ISSUE TITLE
Add notifier options.

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#39]
Use slack as first implementation: [slackclient](https://github.com/slackapi/python-slackclient)

Consider using markdown to format messages: https://api.slack.com/reference/surfaces/formatting

```yml
notifier:
  type: slack:
  notifications:
      500_error:
            """ 
            # {app_name}: Error 500
            Please, check input resource. [link](.....)
            """
```
