### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#6]
It would be nice to add a configuration file, to reduce the configuration points. One option would be to use a yaml.

**Comment by acostapazo** [comment]
This is the result. This will be available on v0.20.0

```yml
app:
  name: taskmanager
  version:
    from_file: VERSION
framework:
    selected_framework: flask
    config_file: swagger.yaml
    port: 8080
    port_env: PETISCO_PORT
logger:
    selected_logger: logging
    name: petisco
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    config_func: taskmanager.src.config.logging_config_func.logging_config_func
persistence:
  config_func: taskmanager.src.config.config_persistence.config_persistence
  models:
    task: taskmanager.src.modules.tasks.infrastructure.persistence.models.task_model.TaskModel
infrastructure:
   services_provider_func: taskmanager.src.config.services_provider.services_provider
   repositories_provider_func: taskmanager.src.config.repositories_provider.repositories_provider
   event_manager_provider_func: taskmanager.src.config.event_manager_provider.event_manager_provider
   publish_deploy_event_func: True
   event_topic: taskmanager
```
