### ISSUE TITLE
Use Task instead cron definitions

### ISSUE THREAD

**Issue by acostapazo** [alice-biometrics/petisco#68]
Now, we can only set cron tasks
```yml
cron:
  dead-letter:
    seconds: 21600 # 6 hours
    handler: eventmanager.src.modules.events.requeue.application.requeue_event.subscribe_to_dead_letter
```

It should be awesome to set task of several types (some cron task, some one-shot tasks)

```yml
tasks:
  dead-letter:
      type: cron
      seconds: 21600 # 6 hours
      handler: petisco.src.subscribe_to_dead_letter
   migrate-database:
      type: environ_activation
      handler: petisco.src.migrate_database
```

**Comment by acostapazo** [comment]
```yml
tasks:
  recurring-task:
    run_in: 5 # seconds
    cron_interval: 10 # seconds
    handler: taskmanager.tasks.recurring_task
  scheduled-task:
    run_in: 10 # seconds
    handler: taskmanager.tasks.scheduled_task
  instant-task:
    handler: taskmanager.tasks.instant_task
```
